[project]
name = "gemini-agent-langchain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3.14",
    "langgraph>=0.2.60",
]
